# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'jelzin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for jelzin
  pod 'Firebase/Core'
  pod 'Firebase/Database'

  target 'jelzinTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'jelzinUITests' do
    # Pods for testing
  end

end
